// Code generated manually following mockery v3 patterns. DO NOT EDIT.
// This follows best practices from github.com/vektra/mockery/v3

package media

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

// ResizeImageWithPadding provides a mock function with given fields: ctx, src, dst, w, h
func (_m *MockProcessor) ResizeImageWithPadding(ctx context.Context, src string, dst string, w int, h int) error {
	ret := _m.Called(ctx, src, dst, w, h)

	if len(ret) == 0 {
		panic("no return value specified for ResizeImageWithPadding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) error); ok {
		r0 = rf(ctx, src, dst, w, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JoinVideos provides a mock function with given fields: ctx, videoPaths, output
func (_m *MockProcessor) JoinVideos(ctx context.Context, videoPaths []string, output string) error {
	ret := _m.Called(ctx, videoPaths, output)

	if len(ret) == 0 {
		panic("no return value specified for JoinVideos")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = rf(ctx, videoPaths, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mockObj := &MockProcessor{}
	mockObj.Mock.Test(t)

	t.Cleanup(func() { mockObj.AssertExpectations(t) })

	return mockObj
}
