// Code generated manually following mockery v3 patterns. DO NOT EDIT.
// This follows best practices from github.com/vektra/mockery/v3

package runpod

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// Submit provides a mock function with given fields: ctx, imageB64, audioB64, opts
func (_m *MockClient) Submit(ctx context.Context, imageB64 string, audioB64 string, opts SubmitOptions) (string, error) {
	ret := _m.Called(ctx, imageB64, audioB64, opts)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, SubmitOptions) (string, error)); ok {
		return rf(ctx, imageB64, audioB64, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, SubmitOptions) string); ok {
		r0 = rf(ctx, imageB64, audioB64, opts)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, SubmitOptions) error); ok {
		r1 = rf(ctx, imageB64, audioB64, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Poll provides a mock function with given fields: ctx, jobID
func (_m *MockClient) Poll(ctx context.Context, jobID string) (PollResult, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 PollResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (PollResult, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) PollResult); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Get(0).(PollResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mockObj := &MockClient{}
	mockObj.Mock.Test(t)

	t.Cleanup(func() { mockObj.AssertExpectations(t) })

	return mockObj
}
