// Code generated manually following mockery v3 patterns. DO NOT EDIT.
// This follows best practices from github.com/vektra/mockery/v3

package storage

import (
	"context"
	"io"

	"github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// SaveTemp provides a mock function with given fields: ctx, name, data
func (_m *MockStorage) SaveTemp(ctx context.Context, name string, data io.Reader) (string, error) {
	ret := _m.Called(ctx, name, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveTemp")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return rf(ctx, name, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = rf(ctx, name, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = rf(ctx, name, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadTemp provides a mock function with given fields: ctx, path
func (_m *MockStorage) LoadTemp(ctx context.Context, path string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for LoadTemp")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CleanupTemp provides a mock function with given fields: ctx, paths
func (_m *MockStorage) CleanupTemp(ctx context.Context, paths []string) error {
	ret := _m.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for CleanupTemp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, paths)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadToS3 provides a mock function with given fields: ctx, key, data
func (_m *MockStorage) UploadToS3(ctx context.Context, key string, data io.Reader) (string, error) {
	ret := _m.Called(ctx, key, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadToS3")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return rf(ctx, key, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = rf(ctx, key, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mockObj := &MockStorage{}
	mockObj.Mock.Test(t)

	t.Cleanup(func() { mockObj.AssertExpectations(t) })

	return mockObj
}
