// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package runpod

import (
	"context"

	"github.com/maauso/infinitetalk-api/internal/runpod"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Poll provides a mock function for the type MockClient
func (_mock *MockClient) Poll(ctx context.Context, jobID string) (runpod.PollResult, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 runpod.PollResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (runpod.PollResult, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) runpod.PollResult); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Get(0).(runpod.PollResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockClient_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockClient_Expecter) Poll(ctx interface{}, jobID interface{}) *MockClient_Poll_Call {
	return &MockClient_Poll_Call{Call: _e.mock.On("Poll", ctx, jobID)}
}

func (_c *MockClient_Poll_Call) Run(run func(ctx context.Context, jobID string)) *MockClient_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Poll_Call) Return(pollResult runpod.PollResult, err error) *MockClient_Poll_Call {
	_c.Call.Return(pollResult, err)
	return _c
}

func (_c *MockClient_Poll_Call) RunAndReturn(run func(ctx context.Context, jobID string) (runpod.PollResult, error)) *MockClient_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type MockClient
func (_mock *MockClient) Submit(ctx context.Context, imageB64 string, audioB64 string, opts runpod.SubmitOptions) (string, error) {
	ret := _mock.Called(ctx, imageB64, audioB64, opts)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, runpod.SubmitOptions) (string, error)); ok {
		return returnFunc(ctx, imageB64, audioB64, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, runpod.SubmitOptions) string); ok {
		r0 = returnFunc(ctx, imageB64, audioB64, opts)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, runpod.SubmitOptions) error); ok {
		r1 = returnFunc(ctx, imageB64, audioB64, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockClient_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - imageB64 string
//   - audioB64 string
//   - opts runpod.SubmitOptions
func (_e *MockClient_Expecter) Submit(ctx interface{}, imageB64 interface{}, audioB64 interface{}, opts interface{}) *MockClient_Submit_Call {
	return &MockClient_Submit_Call{Call: _e.mock.On("Submit", ctx, imageB64, audioB64, opts)}
}

func (_c *MockClient_Submit_Call) Run(run func(ctx context.Context, imageB64 string, audioB64 string, opts runpod.SubmitOptions)) *MockClient_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 runpod.SubmitOptions
		if args[3] != nil {
			arg3 = args[3].(runpod.SubmitOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_Submit_Call) Return(jobID string, err error) *MockClient_Submit_Call {
	_c.Call.Return(jobID, err)
	return _c
}

func (_c *MockClient_Submit_Call) RunAndReturn(run func(ctx context.Context, imageB64 string, audioB64 string, opts runpod.SubmitOptions) (string, error)) *MockClient_Submit_Call {
	_c.Call.Return(run)
	return _c
}
