// Code generated manually following mockery v3 patterns. DO NOT EDIT.
// This follows best practices from github.com/vektra/mockery/v3

package audio

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// MockSplitter is an autogenerated mock type for the Splitter type
type MockSplitter struct {
	mock.Mock
}

// Split provides a mock function with given fields: ctx, inputWav, outputDir, opts
func (_m *MockSplitter) Split(ctx context.Context, inputWav string, outputDir string, opts SplitOpts) ([]string, error) {
	ret := _m.Called(ctx, inputWav, outputDir, opts)

	if len(ret) == 0 {
		panic("no return value specified for Split")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, SplitOpts) ([]string, error)); ok {
		return rf(ctx, inputWav, outputDir, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, SplitOpts) []string); ok {
		r0 = rf(ctx, inputWav, outputDir, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, SplitOpts) error); ok {
		r1 = rf(ctx, inputWav, outputDir, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSplitter creates a new instance of MockSplitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSplitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSplitter {
	mockObj := &MockSplitter{}
	mockObj.Mock.Test(t)

	t.Cleanup(func() { mockObj.AssertExpectations(t) })

	return mockObj
}
