// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package media

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// ExtractLastFrame provides a mock function for the type MockProcessor
func (_mock *MockProcessor) ExtractLastFrame(ctx context.Context, videoPath string) ([]byte, error) {
	ret := _mock.Called(ctx, videoPath)

	if len(ret) == 0 {
		panic("no return value specified for ExtractLastFrame")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, videoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, videoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, videoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessor_ExtractLastFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractLastFrame'
type MockProcessor_ExtractLastFrame_Call struct {
	*mock.Call
}

// ExtractLastFrame is a helper method to define mock.On call
//   - ctx context.Context
//   - videoPath string
func (_e *MockProcessor_Expecter) ExtractLastFrame(ctx interface{}, videoPath interface{}) *MockProcessor_ExtractLastFrame_Call {
	return &MockProcessor_ExtractLastFrame_Call{Call: _e.mock.On("ExtractLastFrame", ctx, videoPath)}
}

func (_c *MockProcessor_ExtractLastFrame_Call) Run(run func(ctx context.Context, videoPath string)) *MockProcessor_ExtractLastFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProcessor_ExtractLastFrame_Call) Return(bytes []byte, err error) *MockProcessor_ExtractLastFrame_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProcessor_ExtractLastFrame_Call) RunAndReturn(run func(ctx context.Context, videoPath string) ([]byte, error)) *MockProcessor_ExtractLastFrame_Call {
	_c.Call.Return(run)
	return _c
}

// JoinVideos provides a mock function for the type MockProcessor
func (_mock *MockProcessor) JoinVideos(ctx context.Context, videoPaths []string, output string) error {
	ret := _mock.Called(ctx, videoPaths, output)

	if len(ret) == 0 {
		panic("no return value specified for JoinVideos")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string) error); ok {
		r0 = returnFunc(ctx, videoPaths, output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessor_JoinVideos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinVideos'
type MockProcessor_JoinVideos_Call struct {
	*mock.Call
}

// JoinVideos is a helper method to define mock.On call
//   - ctx context.Context
//   - videoPaths []string
//   - output string
func (_e *MockProcessor_Expecter) JoinVideos(ctx interface{}, videoPaths interface{}, output interface{}) *MockProcessor_JoinVideos_Call {
	return &MockProcessor_JoinVideos_Call{Call: _e.mock.On("JoinVideos", ctx, videoPaths, output)}
}

func (_c *MockProcessor_JoinVideos_Call) Run(run func(ctx context.Context, videoPaths []string, output string)) *MockProcessor_JoinVideos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcessor_JoinVideos_Call) Return(err error) *MockProcessor_JoinVideos_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessor_JoinVideos_Call) RunAndReturn(run func(ctx context.Context, videoPaths []string, output string) error) *MockProcessor_JoinVideos_Call {
	_c.Call.Return(run)
	return _c
}

// ResizeImageWithPadding provides a mock function for the type MockProcessor
func (_mock *MockProcessor) ResizeImageWithPadding(ctx context.Context, src string, dst string, w int, h int) error {
	ret := _mock.Called(ctx, src, dst, w, h)

	if len(ret) == 0 {
		panic("no return value specified for ResizeImageWithPadding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) error); ok {
		r0 = returnFunc(ctx, src, dst, w, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessor_ResizeImageWithPadding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeImageWithPadding'
type MockProcessor_ResizeImageWithPadding_Call struct {
	*mock.Call
}

// ResizeImageWithPadding is a helper method to define mock.On call
//   - ctx context.Context
//   - src string
//   - dst string
//   - w int
//   - h int
func (_e *MockProcessor_Expecter) ResizeImageWithPadding(ctx interface{}, src interface{}, dst interface{}, w interface{}, h interface{}) *MockProcessor_ResizeImageWithPadding_Call {
	return &MockProcessor_ResizeImageWithPadding_Call{Call: _e.mock.On("ResizeImageWithPadding", ctx, src, dst, w, h)}
}

func (_c *MockProcessor_ResizeImageWithPadding_Call) Run(run func(ctx context.Context, src string, dst string, w int, h int)) *MockProcessor_ResizeImageWithPadding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProcessor_ResizeImageWithPadding_Call) Return(err error) *MockProcessor_ResizeImageWithPadding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessor_ResizeImageWithPadding_Call) RunAndReturn(run func(ctx context.Context, src string, dst string, w int, h int) error) *MockProcessor_ResizeImageWithPadding_Call {
	_c.Call.Return(run)
	return _c
}
