// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audio

import (
	"context"

	"github.com/maauso/infinitetalk-api/internal/audio"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSplitter creates a new instance of MockSplitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSplitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSplitter {
	mock := &MockSplitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSplitter is an autogenerated mock type for the Splitter type
type MockSplitter struct {
	mock.Mock
}

type MockSplitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSplitter) EXPECT() *MockSplitter_Expecter {
	return &MockSplitter_Expecter{mock: &_m.Mock}
}

// Split provides a mock function for the type MockSplitter
func (_mock *MockSplitter) Split(ctx context.Context, inputWav string, outputDir string, opts audio.SplitOpts) ([]string, error) {
	ret := _mock.Called(ctx, inputWav, outputDir, opts)

	if len(ret) == 0 {
		panic("no return value specified for Split")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, audio.SplitOpts) ([]string, error)); ok {
		return returnFunc(ctx, inputWav, outputDir, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, audio.SplitOpts) []string); ok {
		r0 = returnFunc(ctx, inputWav, outputDir, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, audio.SplitOpts) error); ok {
		r1 = returnFunc(ctx, inputWav, outputDir, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSplitter_Split_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Split'
type MockSplitter_Split_Call struct {
	*mock.Call
}

// Split is a helper method to define mock.On call
//   - ctx context.Context
//   - inputWav string
//   - outputDir string
//   - opts audio.SplitOpts
func (_e *MockSplitter_Expecter) Split(ctx interface{}, inputWav interface{}, outputDir interface{}, opts interface{}) *MockSplitter_Split_Call {
	return &MockSplitter_Split_Call{Call: _e.mock.On("Split", ctx, inputWav, outputDir, opts)}
}

func (_c *MockSplitter_Split_Call) Run(run func(ctx context.Context, inputWav string, outputDir string, opts audio.SplitOpts)) *MockSplitter_Split_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 audio.SplitOpts
		if args[3] != nil {
			arg3 = args[3].(audio.SplitOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSplitter_Split_Call) Return(strings []string, err error) *MockSplitter_Split_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSplitter_Split_Call) RunAndReturn(run func(ctx context.Context, inputWav string, outputDir string, opts audio.SplitOpts) ([]string, error)) *MockSplitter_Split_Call {
	_c.Call.Return(run)
	return _c
}
