// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CleanupTemp provides a mock function for the type MockStorage
func (_mock *MockStorage) CleanupTemp(ctx context.Context, paths []string) error {
	ret := _mock.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for CleanupTemp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, paths)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_CleanupTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupTemp'
type MockStorage_CleanupTemp_Call struct {
	*mock.Call
}

// CleanupTemp is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
func (_e *MockStorage_Expecter) CleanupTemp(ctx interface{}, paths interface{}) *MockStorage_CleanupTemp_Call {
	return &MockStorage_CleanupTemp_Call{Call: _e.mock.On("CleanupTemp", ctx, paths)}
}

func (_c *MockStorage_CleanupTemp_Call) Run(run func(ctx context.Context, paths []string)) *MockStorage_CleanupTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CleanupTemp_Call) Return(err error) *MockStorage_CleanupTemp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_CleanupTemp_Call) RunAndReturn(run func(ctx context.Context, paths []string) error) *MockStorage_CleanupTemp_Call {
	_c.Call.Return(run)
	return _c
}

// LoadTemp provides a mock function for the type MockStorage
func (_mock *MockStorage) LoadTemp(ctx context.Context, path string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for LoadTemp")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_LoadTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTemp'
type MockStorage_LoadTemp_Call struct {
	*mock.Call
}

// LoadTemp is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) LoadTemp(ctx interface{}, path interface{}) *MockStorage_LoadTemp_Call {
	return &MockStorage_LoadTemp_Call{Call: _e.mock.On("LoadTemp", ctx, path)}
}

func (_c *MockStorage_LoadTemp_Call) Run(run func(ctx context.Context, path string)) *MockStorage_LoadTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_LoadTemp_Call) Return(readCloser io.ReadCloser, err error) *MockStorage_LoadTemp_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockStorage_LoadTemp_Call) RunAndReturn(run func(ctx context.Context, path string) (io.ReadCloser, error)) *MockStorage_LoadTemp_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTemp provides a mock function for the type MockStorage
func (_mock *MockStorage) SaveTemp(ctx context.Context, name string, data io.Reader) (string, error) {
	ret := _mock.Called(ctx, name, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveTemp")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return returnFunc(ctx, name, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = returnFunc(ctx, name, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = returnFunc(ctx, name, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_SaveTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTemp'
type MockStorage_SaveTemp_Call struct {
	*mock.Call
}

// SaveTemp is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - data io.Reader
func (_e *MockStorage_Expecter) SaveTemp(ctx interface{}, name interface{}, data interface{}) *MockStorage_SaveTemp_Call {
	return &MockStorage_SaveTemp_Call{Call: _e.mock.On("SaveTemp", ctx, name, data)}
}

func (_c *MockStorage_SaveTemp_Call) Run(run func(ctx context.Context, name string, data io.Reader)) *MockStorage_SaveTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_SaveTemp_Call) Return(path string, err error) *MockStorage_SaveTemp_Call {
	_c.Call.Return(path, err)
	return _c
}

func (_c *MockStorage_SaveTemp_Call) RunAndReturn(run func(ctx context.Context, name string, data io.Reader) (string, error)) *MockStorage_SaveTemp_Call {
	_c.Call.Return(run)
	return _c
}

// UploadToS3 provides a mock function for the type MockStorage
func (_mock *MockStorage) UploadToS3(ctx context.Context, key string, data io.Reader) (string, error) {
	ret := _mock.Called(ctx, key, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadToS3")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) (string, error)); ok {
		return returnFunc(ctx, key, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) string); ok {
		r0 = returnFunc(ctx, key, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = returnFunc(ctx, key, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UploadToS3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadToS3'
type MockStorage_UploadToS3_Call struct {
	*mock.Call
}

// UploadToS3 is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data io.Reader
func (_e *MockStorage_Expecter) UploadToS3(ctx interface{}, key interface{}, data interface{}) *MockStorage_UploadToS3_Call {
	return &MockStorage_UploadToS3_Call{Call: _e.mock.On("UploadToS3", ctx, key, data)}
}

func (_c *MockStorage_UploadToS3_Call) Run(run func(ctx context.Context, key string, data io.Reader)) *MockStorage_UploadToS3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_UploadToS3_Call) Return(url string, err error) *MockStorage_UploadToS3_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *MockStorage_UploadToS3_Call) RunAndReturn(run func(ctx context.Context, key string, data io.Reader) (string, error)) *MockStorage_UploadToS3_Call {
	_c.Call.Return(run)
	return _c
}
